# Generated by Django 5.0.2 on 2024-02-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('nID', models.CharField(max_length=12)),
                ('ceoName', models.CharField(max_length=40)),
                ('career', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=12)),
                ('tel', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('nID', models.CharField(max_length=12)),
                ('career', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=12)),
                ('tel', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
    ]
