# Generated by Django 5.0.2 on 2024-02-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='family',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
